{
 "title": "Response Codes",
 "time": { "from": "2026-06-14T21:57:24.322Z", "to": "2026-06-15T04:17:57.295Z" },
 "panels": [
  {
   "title": "Pod Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"prod\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"prod\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum(rate(istio_request_duration_milliseconds_bucket[5m])) by (le, destination_service)\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate by Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total[1m])) by (destination_service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend Canary Traffic v1 vs v2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{destination_service_name=\"backend-service\"}[1m])) by (destination_version)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total[1m])) by (response_code)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}