apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-v2
  namespace: prod
  labels:
    app: backend
    version: v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      version: v2
  template:
    metadata:
      labels:
        app: backend
        version: v2
    spec:
      serviceAccountName: backend-sa
      containers:
        - name: backend
          image: zero-trust-backend:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: APP_VERSION
              value: "v2"